name: LinkedIn Alerts (Hourly)

on:
  schedule:
    - cron: "0 * * * *"   # hourly in UTC



  workflow_dispatch:       # allow manual runs

env:

  TZ: Asia/Kolkata


  PW_CONTEXT: storage      # use storage_state (auth.json) on CI
  HEADLESS: "true"         # headless on Actions

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (pip + Playwright + Chromium)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Restore auth.json from secret
        env:
          AUTH_JSON_B64: ${{ secrets.AUTH_JSON_B64 }}
        run: |
          test -n "$AUTH_JSON_B64" || (echo "Missing AUTH_JSON_B64 secret" && exit 1)
          echo "$AUTH_JSON_B64" | base64 -d > auth.json
          ls -lh auth.json
      - name: Webhook self-test
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          set -euo pipefail
          echo 'Posting test message to Slack…'
          RESP=$(curl -s -w " HTTP_STATUS:%{http_code}\n" -X POST \
            -H "Content-type: application/json" \
            --data '{"text":"Webhook test from GitHub Actions ✅"}' \
            "$SLACK_WEBHOOK_URL")
          echo "$RESP"
          # Fail the job if Slack didn’t say 200 OK
          STATUS=$(echo "$RESP" | sed -n 's/.*HTTP_STATUS:\(.*\)$/\1/p')
          [ "$STATUS" = "200" ] || (echo "Slack webhook failed with HTTP $STATUS" && exit 1)

      - name: Run alerts
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python linkedin_alerts.py

      - name: Upload Playwright trace
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trace
          path: trace.zip

      - name: Upload debug screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-shots
          path: search_*.png












